{% set version = "15.0.5" %}

package:
  name: flang-split
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: 9c4278a6b8884eb7f4ae7dfe3c8e5445019824885e47cfdf1392563c47316fd6

build:
  number: 0
  track_features:
    - flang

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - clangdev =={{ version }}
    - compiler-rt =={{ version }}
    - lit =={{ version }}
    - llvm-openmp =={{ version }}
    - llvmdev =={{ version }}
    - mlir =={{ version }}

test:
  commands:
    - flang --version

outputs:
  - name: libflang
    script: install_libflang.sh   # [unix]
    script: install_libflang.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - clangdev =={{ version }}
        - compiler-rt =={{ version }}
        - llvm-openmp =={{ version }}
        - llvmdev =={{ version }}
        - mlir =={{ version }}
      run:
        - llvm-openmp =={{ version }}

  - name: flang
    script: install_flang.sh      # [unix]
    script: install_flang.bat     # [win]
    run_exports:
      strong:
        - libflang >={{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - clangdev =={{ version }}
        - compiler-rt =={{ version }}
        - llvm-openmp =={{ version }}
        - llvmdev =={{ version }}
        - mlir =={{ version }}
      run:
        - clangdev =={{ version }}
        - llvm-openmp =={{ version }}
        - {{ pin_subpackage('libflang', exact=True) }}
    test:
      files:
        - hello_world.f90
      commands:
        # TODO - Figure out why the following line is needed.
        - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64  # [win64]
        - flang hello_world.f90
        - ./a.out   # [unix]
        - a.exe     # [win]

  - name: flang_{{ target_platform }}
    run_exports:
      strong:
        - libflang >={{ version }}
    requirements:
      - {{ pin_subpackage('flang', exact=True) }}


about:
  home: https://flang.llvm.org
  license: Apache-2.0
  license_file: flang/LICENSE.TXT
  summary: Flang is a Fortran compiler targeting LLVM.
  dev_url: https://github.com/llvm/llvm-project

extra:
  recipe-maintainers:
    - isuruf
    - wolfv
  feedstock-name: flang
