{% set clang_variant = os.environ.get('CLANG_VARIANT', 'flang') %}
{% set flang_commit = "1192ff0775ddf94f7944dc40181406c088b4d575" %}
{% set llvm_version = "11.0.1" %}
{% set version = llvm_version %}
{% set sha256 = "e4fa46a0b29cabf4c4583231b79f923d6296efc4196099cbaebf5828f03a2607" %}
{% set build_number = "20210131" %}

package:
  name: flang-split
  version: {{ version }}

source:
  url: https://github.com/xoviat/flang/archive/{{ flang_commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: true    # [osx]
  skip: true    # [unix]
  skip: true    # [win32]
  skip: true    # [win and vc<14]
  track_features:
    - flang

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - m2-sed   # [win]
    - m2-gawk  # [win]
    - m2-grep  # [win]
  host:
    - clangdev =={{ llvm_version }}
    - llvm-openmp =={{ llvm_version }}
    - llvmdev =={{ llvm_version }}

test:
  commands:
    - flang --version

outputs:
  - name: libflang
    script: install_libflang.sh   # [unix]
    script: install_libflang.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - m2-sed   # [win]
        - m2-gawk  # [win]
        - m2-grep  # [win]
      host:
        - clangdev =={{ llvm_version }}
        - llvm-openmp =={{ llvm_version }}
        - llvmdev =={{ llvm_version }}
      run:
        - llvm-openmp =={{ llvm_version }}

  - name: flang
    script: install_flang.sh      # [unix]
    script: install_flang.bat     # [win]
    run_exports:
      strong:
        - libflang >={{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - m2-sed   # [win]
        - m2-gawk  # [win]
        - m2-grep  # [win]
      host:
        - clangdev =={{ llvm_version }}
        - llvm-openmp =={{ llvm_version }}
        - llvmdev =={{ llvm_version }}
      run:
        - clangdev =={{ llvm_version }}
        - llvm-openmp =={{ llvm_version }}
        - {{ pin_subpackage('libflang', exact=True) }}
    test:
      files:
        - hello_world.f90
      commands:
        # TODO - Figure out why the following line is needed.
        - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64  # [win64]
        - flang hello_world.f90
        - ./a.out   # [unix]
        - a.exe     # [win]

  - name: flang_{{ target_platform }}
    run_exports:
      strong:
        - libflang >={{ version }}
    requirements:
      - {{ pin_subpackage('flang', exact=True) }}


about:
  home: http://github.com/flang-compiler/flang
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Flang is a Fortran compiler targeting LLVM.

extra:
  recipe-maintainers:
    - isuruf
  feedstock-name: flang
