{% set clang_variant = os.environ.get('CLANG_VARIANT', 'flang') %}
{% set flang_commit = "4ddc948697091af68df0a1c63d18e700af047eba" %}
{% set llvm_version = "5.0.0" %}
{% set version = llvm_version %}
{% set sha256 = "7078a7b24bb2b52789fc5551bd6eeee19082e2923e4d49c2834579e51b43ea74" %}
{% set build_number = 20181525 %}

package:
  name: flang
  version: {{ version }}

source:
  url: https://github.com/isuruf/flang/archive/{{ flang_commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: true    # [osx]
  skip: true    # [win32]
  skip: true    # [win and vc<14]
  track_features:
    - flang

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - clangdev =={{ llvm_version }}
    - openmp =={{ llvm_version }}
    - llvmdev =={{ llvm_version }}
    - flang-meta
  host:

test:
  commands:
    - flang --version

outputs:
  - name: libflang
    script: install_libflang.sh   # [unix]
    script: install_libflang.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - clangdev =={{ llvm_version }}
        - openmp =={{ llvm_version }}
        - llvmdev =={{ llvm_version }}
        - flang-meta
      host:
      run:
        - openmp =={{ llvm_version }}

  - name: flang
    script: install_flang.sh      # [unix]
    script: install_flang.bat     # [win]
    run_exports:
      strong:
        - libflang >={{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - clangdev =={{ llvm_version }}
        - openmp =={{ llvm_version }}
        - llvmdev =={{ llvm_version }}
        - flang-meta
      host:
      run:
        - clangdev =={{ llvm_version }}
        - openmp =={{ llvm_version }}
        - {{ pin_subpackage('libflang', exact=True) }}
    test:
      files:
        - hello_world.f90
      commands:
        # TODO - Figure out why the following line is needed.
        - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64  # [win64]
        - flang hello_world.f90
        - ./a.out   # [unix]
        - a.exe     # [win]

  - name: flang_{{ target_platform }}
    run_exports:
      strong:
        - libflang >={{ version }}
    requirements:
      - {{ pin_subpackage('flang', exact=True) }}


about:
  home: http://github.com/flang-compiler/flang
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: Flang is a Fortran compiler targeting LLVM.

extra:
  recipe-maintainers:
    - isuruf
