{% set version = "21.1.1" %}

package:
  name: flang-split
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version.replace(".rc", "-rc") }}.tar.gz
  sha256: 5f048351ee63050d7fa45b6a1160768fb222a8d306a89e1344515ef7a4bcd278

build:
  number: 0
  # intentionally only windows (main target) & linux (debuggability)
  skip: true  # [osx]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    # some bug with misinterpreting `...\tools` as a tab (`\t`)
    - ninja <1.13
    - mlir =={{ version }}     # [build_platform != target_platform]
    # for showing CPU info of CI agent
    - numpy *
  host:
    - clangdev =={{ version }}
    - compiler-rt =={{ version }}
    - lit =={{ version }}
    - llvmdev =={{ version }}
    - mlir =={{ version }}
    - zlib

outputs:
  - name: flang
    script: install_flang.sh  # [unix]
    script: install_flang.bat  # [win]
    requirements:
      build:
        - cmake
        - ninja <1.13
        # for strong run-exports
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - clangdev =={{ version }}
        - compiler-rt =={{ version }}
        - llvmdev =={{ version }}
        - mlir =={{ version }}
        # for required run-exports
        - llvm =={{ version }}
        - libclang-cpp =={{ version }}
        # ninja really wants to find z.lib on win
        - zlib  # [win]
        - zstd  # [win]
      run:
        - sysroot_{{ target_platform }} >={{ c_stdlib_version }}    # [linux]
        - clang =={{ version }}
        - compiler-rt =={{ version }}   # [win]
    test:
      commands:
        - test -f $PREFIX/bin/flang                     # [linux]
        - if not exist %LIBRARY_BIN%\flang.exe exit 1   # [win]

about:
  home: https://flang.llvm.org
  license: Apache-2.0
  license_file: flang/LICENSE.TXT
  summary: Flang is a Fortran compiler targeting LLVM.
  dev_url: https://github.com/llvm/llvm-project

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
  feedstock-name: flang
