azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 15GiB
  settings_win:
    variables:
      SET_PAGEFILE: "True"
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
