appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dNDBS2JLpXAFabTPh3kGnLpWbxwHhhIc1zjMjHFowDCgyn4PGgfQIq7grcsoRmcQA65iYk1+PKSto9nYMyWjV0nQmlSkqRn8tOi1R6sCQwLKmUUPBIfHE5R6F9XGsDgjZPl9hcWKHMXtROtdBixS/36vkrKaLOUzPvxoiCQquV1Di9JGbYwyNbw9g1I2lSkmavg2yxEBdcjvA1OST9yq6bYlvlLp7j/Dc0CDoYRpKR43b3uW7RnILK6NM1p97MmWf/M5tF/E2ha4x0OMb/NSvKeAkUFGMUky5cmT0siGZI+1K3CpxyiIb5tPNEQTzQ8XmKIYZLLJqVZQhIigJygQthaP0ELLoVWl3PYvpJ7F8LWjJ3akApQrNGZlHYupvsPy9IMNhdf9R0px94zSAsJhGuZE2GPkBtnrqY2YmUpdSD2hROfhn3UoyiXmHvj5Z5ZnEtiaXtBafafdRtVTwVaLuP1kqLDp+KkQZ61l0fqRomZS8jKihg8JTbQDYUgPwOA9XpvNN7EMcY1IXt/3qTmrk2Oxo7MrSseMtzzozKMWbjn2ycsmBmtf+S240N1Jya5z4z9lbG4YnGKUF9Q8APKXCEqPEaJuupMRlczQxY4bNA03Tn/RQAGaWIG6SKFFuNxFAvgyUt+WHOX7FBidgEApbcVUfILEpycHLGWmjqfzf+s=}
