conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
provider:
  win_arm64: default
workflow_settings:
  build_workspace_dir:
    - value: C:\bld
      os: win
  pagefile_size:
    - value: 16
      os: win
  tools_install_dir:
    - value: C:\Miniforge
      os: win
